[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
data_reader = "5yjGzs7MYLUeDyr9vVNeNWbu3Tpcpbnt52ufdmmPUuL2"
read_data_from_other_program_account = "9USSFP6mixXwvoBeC66oLgg1GxnD1qyNFewwFmTFDCsY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
