[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_acc_ownership_in_program = "EAtEWN93PjtQcWxGGnHAF7S4EDq1y461pUvpLJzTXTPE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
