[workspace]
members = ["programs/*"]
resolver = "2"

[profile.release]
# overflow-checks = true # Rust will add overflow checks at the compiler level
overflow-checks = false
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
